### ISSUE TITLE
Curious

### ISSUE THREAD

**Issue by alphapapa** [vermiculus/stash.el#3]
Hi again,

I also just discovered this.  It looks very cool!  I'm curious, since no packages on MELPA seem to depend on it, and since it hasn't been updated in 4 years, what is its status?  Is there any reason I shouldn't use it?  Do you use it for anything in your config or off-MELPA packages?

There seem to be a few packages similar to this, for example I discovered this recently: https://github.com/doublep/extmap, and then there's https://github.com/raxod502/prescient.el which has [similar functionality](https://github.com/raxod502/prescient.el/issues/8) that could be factored out of it, and, of course, there's the built-in `savehist`, and `desktop`, and then `recentf` does some of its own persisting.

It would be nice if there were a "best" or "recommended" way to do this common task.

I'll be adding `stash` and `package-demo` to https://github.com/alphapapa/emacs-package-dev-handbook.  :)

**Comment by vermiculus** [comment]
I believe it was factored out of sx.el – with sx.el maintaining its caching system instead of using the dependency. I don't believe there's any reason to not use it other than the availability of other, more maintained solutions :-)

This is also on my list to resurrect (only about ten projects, incl. sx.el and magithub).

**Comment by alphapapa** [comment]
Thanks.
